server:
    port: TU_PUERTO

spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: TU_CLIENT_ID
                        clientSecret: TU_CLIENT_SECRET
                        scope:
                            - email
                            - profile
                            - openid
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
        ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect